#ifndef PPCNN_DEFINE_HPP
#define PPCNN_DEFINE_HPP

#define PPCNN_TIMEOUT_SEC (60)
#define PPCNN_RETRY_INTERVAL_USEC (2000000)

#define PPCNN_DEFAULT_MAX_CONCURRENT_QUERIES 128
#define PPCNN_DEFAULT_MAX_RESULTS 128
#define PPCNN_DEFAULT_MAX_RESULT_LIFETIME_SEC 50000

#endif /* PPCNN_DEFINE_HPP */
