#ifndef PPCNN_DEFINE_HPP
#define PPCNN_DEFINE_HPP

#define PPCNN_TIMEOUT_SEC (60)
#define PPCNN_RETRY_INTERVAL_USEC (2000000)

#define PPCNN_DEFAULT_MAX_CONCURRENT_QUERIES 128
#define PPCNN_DEFAULT_MAX_RESULTS 128
#define PPCNN_DEFAULT_MAX_RESULT_LIFETIME_SEC 50000

#define PPCNN_DEFAULT_PLAINTEXT_EXPERIMENT_PATH "../../../plaintext_experiment/"
#define PPCNN_DEFAULT_DATASETS_PATH "../../../datasets/"

#endif /* PPCNN_DEFINE_HPP */
